#!/usr/bin/env python3
"""Exercise the paths that need model weights, which CI cannot reach.

Every automated test in this repository runs against the deterministic
embedder and never opens a PDF. That is not a gap in coverage so much as a
boundary: the environment the suite runs in cannot download model weights, so
three claims have never been checked against anything real.

This script checks them. Run it on a machine with network access to the model
host, or inside an image built with `--build-arg PREFETCH_MODELS=true`.

    python scripts/verify_model_paths.py

It writes to a temporary directory and removes it. It touches no corpus of
yours, and it prints what it proved rather than a bare "ok" — a green run here
is meant to be quotable evidence, not reassurance.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
import traceback
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

PASS, FAIL, SKIP = "PASS", "FAIL", "SKIP"
results: list[tuple[str, str, str]] = []


def record(name: str, status: str, detail: str = "") -> None:
    results.append((name, status, detail))
    mark = {PASS: "✓", FAIL: "✗", SKIP: "–"}[status]
    print(f"  {mark} {name}" + (f" — {detail}" if detail else ""))


def _pdf_bytes() -> bytes:
    """A minimal one-page PDF with real, extractable text.

    Written by hand rather than generated by a library, so this script pulls in
    no dependency the project does not already have. The text is synthetic:
    no real case material belongs in this repository.
    """
    body = b"BT /F1 12 Tf 72 720 Td (Northgate Holdings signed the harbour lease.) Tj ET"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(body)).encode() + b" >>\nstream\n" + body + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{index} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode() + b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n".encode()
        + b"%%EOF\n"
    )
    return bytes(out)


def check_pdf_extraction(workspace: Path) -> None:
    """Docling's layout models, which need weights on first use."""
    from jackryan.ingestion.router import FormatRouter

    path = workspace / "lease.pdf"
    path.write_bytes(_pdf_bytes())
    try:
        extraction = FormatRouter().extract(path)
    except Exception as exc:
        record("PDF extraction", FAIL, f"{type(exc).__name__}: {exc}")
        return

    text = extraction.text
    if "Northgate" not in text:
        record(
            "PDF extraction",
            FAIL,
            f"extractor ran but recovered no expected text; got {text[:120]!r}",
        )
        return
    record(
        "PDF extraction",
        PASS,
        f"{extraction.extractor} recovered {len(text)} chars including the expected phrase",
    )


def check_real_embedder(workspace: Path) -> None:
    """The contract's embed_model and embed_dimensions, against actual vectors.

    The dimension is the part that matters: it sizes the vector index, it is
    part of the corpus fingerprint, and nothing has ever confirmed the shipped
    default matches what the model actually produces.
    """
    from jackryan.config import Contract
    from jackryan.embedding.model import ModelEmbedder

    contract = Contract()
    embedder = ModelEmbedder(
        model_name=contract.embed_model,
        dimensions=contract.embed_dimensions,
        cache_dir=str(workspace / "models"),
    )
    try:
        vectors = embedder.embed_documents(["The harbour lease was signed in March."])
    except Exception as exc:
        record("Real embedder loads", FAIL, f"{type(exc).__name__}: {exc}")
        return
    record("Real embedder loads", PASS, f"model {contract.embed_model}")

    width = len(vectors[0])
    if width != contract.embed_dimensions:
        record(
            "Contract width matches the model",
            FAIL,
            f"contract says {contract.embed_dimensions}, model produced {width} — "
            "the contract default is wrong and every corpus built on it is mis-sized",
        )
        return
    record("Contract width matches the model", PASS, f"{width} dimensions, as declared")

    # e5 is asymmetric: a passage and a query are prefixed differently, and
    # getting that backwards degrades retrieval quietly rather than loudly.
    query = embedder.embed_query("who signed the harbour lease")
    if len(query) != width:
        record("Query and passage widths agree", FAIL, f"query {len(query)} vs passage {width}")
        return
    record("Query and passage widths agree", PASS, f"both {width}")


def check_end_to_end(workspace: Path) -> None:
    """A real ingest with real embeddings, searched and cited.

    This is the claim the whole prototype rests on, and it has only ever been
    made against a stand-in embedder.
    """
    from jackryan.app import build_context
    from jackryan.config import Config, Contract, Profile

    config = Config(
        contract=Contract(),
        profile=Profile(name="verify", embedder="model"),
        data_dir=workspace / "data",
    )
    try:
        context = build_context(config)
    except Exception as exc:
        record("End-to-end with real embeddings", FAIL, f"context: {type(exc).__name__}: {exc}")
        return

    try:
        casefile = context.casefiles.create("Model Path Verification")
        corpus = workspace / "corpus"
        corpus.mkdir(exist_ok=True)
        (corpus / "lease.md").write_text(
            "# Harbour Lease\n\n"
            "Northgate Holdings was awarded the harbour lease in March 2021 "
            "by the port authority board.\n",
            encoding="utf-8",
        )
        (corpus / "lease.pdf").write_bytes(_pdf_bytes())

        report = context.ingestion.ingest(casefile.short_id, corpus)
        if report.failed:
            detail = "; ".join(o.detail for o in report.outcomes if o.status == "failed")
            record("End-to-end with real embeddings", FAIL, f"ingest failures: {detail}")
            return

        # This query shares content words with the corpus ("was", "awarded",
        # "lease"), so keyword retrieval alone could satisfy it. What the check
        # below establishes is that the vector leg ran and returned something —
        # `vector_rank` is set — not that semantic retrieval beat keywords.
        # Retrieval quality is a separate question and is not measured here.
        hits = context.search.search(casefile.short_id, "who was awarded the lease", limit=3)
        if not hits:
            record(
                "End-to-end with real embeddings",
                FAIL,
                "ingested but retrieved nothing for a paraphrased query",
            )
            return
        semantic = [h for h in hits if h.vector_rank is not None]
        record(
            "End-to-end with real embeddings",
            PASS,
            f"{report.ingested} documents, {len(hits)} hits, "
            f"{len(semantic)} found by vector search",
        )
    finally:
        context.close()


def check_mcp_surface(workspace: Path) -> None:
    """Whether an agent can be pointed at this instance at all.

    This script cannot verify the part that actually matters — that a live
    model *chooses* the right tools from their descriptions. It verifies the
    surface answers, which is the precondition. Driving it with two model
    vendors remains a human step; see docs/handover.md.
    """
    import anyio

    from jackryan.app import build_context
    from jackryan.config import Config, Contract, Profile
    from jackryan.interfaces.mcp import build_mcp_server

    config = Config(
        contract=Contract(),
        profile=Profile(name="verify", embedder="model"),
        data_dir=workspace / "mcp-data",
    )
    context = build_context(config)
    try:
        casefile = context.casefiles.create("Surface Check")
        corpus = workspace / "mcp-corpus"
        corpus.mkdir(exist_ok=True)
        (corpus / "note.md").write_text(
            "# Note\n\nThe port authority board deferred the tariff decision.\n",
            encoding="utf-8",
        )
        context.ingestion.ingest(casefile.short_id, corpus)
        server = build_mcp_server(context)

        async def drive():
            import json

            result = await server.call_tool(
                "case_search",
                {"casefile": casefile.short_id, "query": "what did the board defer", "limit": 3},
            )
            payload = json.loads(result.content[0].text)
            if not payload.get("results"):
                return None
            cited = await server.call_tool(
                "case_cite",
                {
                    "casefile": casefile.short_id,
                    "chunk_id": payload["results"][0]["chunk_id"],
                },
            )
            return json.loads(cited.content[0].text)

        citation = anyio.run(drive)
        if not citation or "citation" not in citation:
            record("MCP surface answers with a citation", FAIL, "search or cite returned nothing")
            return
        record("MCP surface answers with a citation", PASS, citation["citation"][:80])
    except Exception as exc:
        record("MCP surface answers with a citation", FAIL, f"{type(exc).__name__}: {exc}")
    finally:
        context.close()


CHECKS = {
    "pdf": ("PDF extraction (Docling layout models)", check_pdf_extraction),
    "embedder": ("The real embedder and the contract width", check_real_embedder),
    "end-to-end": ("A real ingest, searched with real vectors", check_end_to_end),
    "mcp": ("The MCP surface, driven in process", check_mcp_surface),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--only",
        choices=sorted(CHECKS),
        action="append",
        help="run one check rather than all of them; repeatable",
    )
    parser.add_argument("--keep", action="store_true", help="leave the temporary directory in place")
    args = parser.parse_args()

    selected = args.only or list(CHECKS)
    workspace = Path(tempfile.mkdtemp(prefix="jackryan-verify-"))
    print(f"Workspace: {workspace}\n")

    try:
        for key in selected:
            title, func = CHECKS[key]
            print(f"{title}")
            try:
                func(workspace)
            except Exception:
                record(title, FAIL, "raised before it could report")
                traceback.print_exc()
            print()
    finally:
        if args.keep:
            print(f"Left in place: {workspace}")
        else:
            shutil.rmtree(workspace, ignore_errors=True)

    failed = [r for r in results if r[1] == FAIL]
    passed = [r for r in results if r[1] == PASS]
    print("─" * 60)
    print(f"{len(passed)} passed, {len(failed)} failed")
    if failed:
        print("\nFailures:")
        for name, _, detail in failed:
            print(f"  ✗ {name}: {detail}")
        print(
            "\nA failure here is a real finding, not a flaky environment: these are "
            "the paths nothing else in this repository exercises."
        )
        return 1
    print(
        "\nThese four claims now rest on something that ran, rather than on a "
        "deterministic stand-in. Record the result in docs/handover.md."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
