#!/usr/bin/env python3
"""Exercise the paths that need model weights, which CI cannot reach.

Every automated test in this repository runs against the deterministic
embedder, never opens a PDF, and never builds a recognition engine. That is not
a gap in coverage so much as a boundary: the environment the suite runs in
cannot download model weights, so several claims have never been checked
against anything real.

This script checks them. Run it on a machine with network access to the model
host, or inside an image built with `--build-arg PREFETCH_MODELS=true`.

    python scripts/verify_model_paths.py
    python scripts/verify_model_paths.py --only vlm   # downloads a vision model

It writes to a temporary directory and removes it. It touches no corpus of
yours, and it prints what it proved rather than a bare "ok" — a green run here
is meant to be quotable evidence, not reassurance.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
import traceback
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

PASS, FAIL, SKIP = "PASS", "FAIL", "SKIP"
results: list[tuple[str, str, str]] = []


def record(name: str, status: str, detail: str = "") -> None:
    results.append((name, status, detail))
    mark = {PASS: "✓", FAIL: "✗", SKIP: "–"}[status]
    print(f"  {mark} {name}" + (f" — {detail}" if detail else ""))


def _pdf_bytes() -> bytes:
    """A minimal one-page PDF with real, extractable text.

    Written by hand rather than generated by a library, so this script pulls in
    no dependency the project does not already have. The text is synthetic:
    no real case material belongs in this repository.
    """
    body = b"BT /F1 12 Tf 72 720 Td (Northgate Holdings signed the harbour lease.) Tj ET"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(body)).encode() + b" >>\nstream\n" + body + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{index} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode() + b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n".encode()
        + b"%%EOF\n"
    )
    return bytes(out)


def check_pdf_extraction(workspace: Path) -> None:
    """Docling's layout models, which need weights on first use."""
    from jackryan.ingestion.router import FormatRouter

    path = workspace / "lease.pdf"
    path.write_bytes(_pdf_bytes())
    try:
        extraction = FormatRouter().extract(path)
    except Exception as exc:
        record("PDF extraction", FAIL, f"{type(exc).__name__}: {exc}")
        return

    text = extraction.text
    if "Northgate" not in text:
        record(
            "PDF extraction",
            FAIL,
            f"extractor ran but recovered no expected text; got {text[:120]!r}",
        )
        return
    record(
        "PDF extraction",
        PASS,
        f"{extraction.extractor} recovered {len(text)} chars including the expected phrase",
    )


# Recognition is checked against a page that carries no text layer at all, in
# the three languages this workbench is for. The fixture is drawn rather than
# typeset, because a PDF with a text layer would prove nothing here: the first
# rung would read it and recognition would never run.
CYRILLIC_FONTS = (
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    "/usr/share/fonts/TTF/DejaVuSans.ttf",
)
SCAN_UK = "Правління передало оренду компанії Нортгейт"
SCAN_RU = "Аренда передана компании Нортгейт советом"
SCAN_EN = "The board awarded the harbour lease to Northgate"


def _find_cyrillic_font() -> str | None:
    for candidate in CYRILLIC_FONTS:
        if Path(candidate).exists():
            return candidate
    return None


def _scan_pdf(path: Path, font_path: str) -> None:
    """An image-only PDF: three lines drawn as pixels, with no text layer."""
    from PIL import Image, ImageDraw, ImageFont

    image = Image.new("RGB", (2200, 700), "white")
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(font_path, 46)
    y = 80
    for line in (SCAN_UK, SCAN_RU, SCAN_EN):
        draw.text((80, y), line, fill="black", font=font)
        y += 130
    image.save(path, "PDF", resolution=200.0)


def _similarity(expected: str, text: str) -> float:
    """How closely `text` contains `expected`, as a ratio in 0..1.

    Similarity rather than exact match, because recognition is not letter
    perfect and pretending otherwise makes a brittle check that fails for the
    wrong reason. The `eslav` model reads "Правління" as "Правлиння" — a real
    limitation, recorded in the change's design, and not the thing this is
    testing. What separates a working configuration from a broken one here is
    not one character: it is 0.85 against 0.11.
    """
    import difflib

    want = " ".join(expected.split()).lower()
    flat = " ".join(text.split()).lower()
    if not flat:
        return 0.0
    window = len(want) + 12
    return max(
        (
            difflib.SequenceMatcher(None, want, flat[start : start + window]).ratio()
            for start in range(0, max(1, len(flat) - len(want) + 12))
        ),
        default=0.0,
    )


# Comfortably below what a correct configuration scores and far above what a
# Latin-only model does. The gap measured on this fixture is 0.85 versus 0.11,
# so this is not a threshold that needs tuning.
RECOGNISED = 0.75


def check_recognition(workspace: Path) -> None:
    """The quality gate escalating a scan, in English, Ukrainian and Russian.

    This is the check the whole extraction-quality-gate change exists for. What
    it must establish is not "OCR ran" but "OCR ran with the configured language
    and recovered Cyrillic", because the defect being fixed was an engine that
    recovered English perfectly and dropped Ukrainian and Russian entirely.

    So it runs twice. Once with the shipped `eslav` default, which must recover
    all three; once forced to `en`, which must not recover the Cyrillic. Without
    the second run the first cannot fail for the reason it claims to test.
    """
    from jackryan.ingestion.quality_gate import OCR, QualityGate

    font_path = _find_cyrillic_font()
    if font_path is None:
        record(
            "Recognition of a scan",
            SKIP,
            "no font with Cyrillic coverage found; tried " + ", ".join(CYRILLIC_FONTS),
        )
        return

    path = workspace / "scan.pdf"
    _scan_pdf(path, font_path)
    if b"BT" in path.read_bytes():
        record(
            "Recognition of a scan",
            FAIL,
            "the fixture grew a text layer, so it would not exercise recognition",
        )
        return

    try:
        reading = QualityGate(
            ocr_engine="rapidocr", ocr_language="eslav", min_chars_per_page=100
        ).read(path)
    except Exception as exc:
        record("Recognition of a scan", FAIL, f"{type(exc).__name__}: {exc}")
        return

    if reading.source != OCR:
        record(
            "Recognition of a scan",
            FAIL,
            f"a page with no text layer was read as {reading.source!r}, not by recognition",
        )
        return

    scores = {
        "uk": _similarity(SCAN_UK, reading.text),
        "ru": _similarity(SCAN_RU, reading.text),
        "en": _similarity(SCAN_EN, reading.text),
    }
    shown = " ".join(f"{code}={score:.2f}" for code, score in scores.items())
    if min(scores.values()) < RECOGNISED:
        record(
            "Recognition of a scan",
            FAIL,
            f"recovered {shown} against a floor of {RECOGNISED}; "
            f"got {reading.text[:160]!r}",
        )
        return
    record(
        "Recognition of a scan",
        PASS,
        f"escalated to {reading.source} and recovered all three languages from a page "
        f"with no text layer ({shown})",
    )

    # The negative. Forcing a Latin-only recognition model must lose the
    # Cyrillic — which is exactly what the shipped configuration used to do to
    # every Ukrainian and Russian scan. Without this, the check above could pass
    # on an engine that ignored the language setting entirely.
    try:
        latin_only = QualityGate(
            ocr_engine="rapidocr", ocr_language="en", min_chars_per_page=100
        ).read(path)
    except Exception as exc:
        record("Recognition language matters", FAIL, f"{type(exc).__name__}: {exc}")
        return

    lost = {
        "uk": _similarity(SCAN_UK, latin_only.text),
        "ru": _similarity(SCAN_RU, latin_only.text),
    }
    if max(lost.values()) >= RECOGNISED:
        record(
            "Recognition language matters",
            FAIL,
            f"a Latin-only model still scored {lost}, so the check above does not "
            "establish that the language setting is what recovers the Cyrillic",
        )
        return
    record(
        "Recognition language matters",
        PASS,
        "forced to 'en' the same page scores "
        + " ".join(f"{code}={score:.2f}" for code, score in lost.items())
        + f" — below {RECOGNISED}, so the language setting is what recovers them",
    )

    # The fail-open guard, which nothing else exercises. A DocumentConverter
    # builds its pipelines lazily, so one constructed with a nonsense language
    # returns quite happily and fails on the first scan instead. check_engine
    # calls initialize_pipeline for exactly this reason, and only a real engine
    # can show that the difference is real.
    from jackryan.ingestion.quality_gate import RecognitionError, build_converter, check_engine

    lazy_construction_succeeded = False
    try:
        build_converter(OCR, engine="rapidocr", language="nosuchlanguage")
        lazy_construction_succeeded = True
    except Exception:
        pass

    try:
        check_engine("rapidocr", "nosuchlanguage")
    except RecognitionError as exc:
        if not lazy_construction_succeeded:
            record(
                "A misconfigured engine is refused",
                PASS,
                "the language was refused, though constructing the converter also failed, "
                "so this run does not show that building the pipeline is what caught it",
            )
        elif "nosuchlanguage" in str(exc):
            record(
                "A misconfigured engine is refused",
                PASS,
                "constructing the converter succeeded and initialising the pipeline "
                "refused the language — which is why the check builds it rather than "
                "holding it",
            )
        else:
            record(
                "A misconfigured engine is refused",
                FAIL,
                f"refused, but the message does not name the setting: {exc}",
            )
    except Exception as exc:
        record("A misconfigured engine is refused", FAIL, f"{type(exc).__name__}: {exc}")
    else:
        record(
            "A misconfigured engine is refused",
            FAIL,
            "a language the engine cannot serve was accepted, so a misconfigured "
            "instance would ingest every scan as an empty document",
        )


def check_vision_rung(workspace: Path) -> None:
    """The third rung, against a real vision model.

    Not run by default: it downloads model weights measured in hundreds of
    megabytes. `--only vlm` asks for it deliberately.
    """
    from jackryan.ingestion.quality_gate import VLM, QualityGate, build_converter

    font_path = _find_cyrillic_font()
    if font_path is None:
        record("Vision rung", SKIP, "no font with Cyrillic coverage found")
        return

    path = workspace / "vision.pdf"
    _scan_pdf(path, font_path)

    # Read at the vision rung directly. Going through the ladder cannot answer
    # this: with a floor nothing clears, the richest attempt wins, and OCR's
    # output beat the vision model's — so a check on the ladder's result would
    # have passed without the vision model producing anything at all. What
    # needs proving here is narrower and real: that a vision model loads and
    # reads a page. Which rung the ladder then prefers is policy, covered
    # offline by the unit tests.
    model = "GRANITEDOCLING_TRANSFORMERS"
    try:
        converter = build_converter(
            VLM, engine="rapidocr", language="eslav", vlm_model=model
        )
        document = converter.convert(str(path)).document
        text = document.export_to_markdown().strip()
    except Exception as exc:
        record("Vision rung", FAIL, f"{model}: {type(exc).__name__}: {exc}")
        return

    if not text:
        record(
            "Vision rung",
            FAIL,
            f"{model} loaded and ran but returned no text for a page with legible content",
        )
        return
    record(
        "Vision rung",
        PASS,
        f"{model} loaded and read the page, returning {len(text)} chars: "
        f"{' '.join(text.split())[:90]!r}",
    )

    # And that the ladder does place it last, reached only after the two rungs
    # above it have failed to clear the floor.
    gate = QualityGate(
        ocr_engine="rapidocr",
        ocr_language="eslav",
        min_chars_per_page=100,
        vlm_model=model,
    )
    if gate.rungs()[-1] != VLM:
        record(
            "Vision rung is last",
            FAIL,
            f"configured rungs are {gate.rungs()}, so the vision model is not the last resort",
        )
        return
    record(
        "Vision rung is last",
        PASS,
        f"configured rungs are {gate.rungs()}",
    )


def check_real_embedder(workspace: Path) -> None:
    """The contract's embed_model and embed_dimensions, against actual vectors.

    The dimension is the part that matters: it sizes the vector index, it is
    part of the corpus fingerprint, and nothing has ever confirmed the shipped
    default matches what the model actually produces.
    """
    from jackryan.config import Contract
    from jackryan.embedding.model import ModelEmbedder

    contract = Contract()
    embedder = ModelEmbedder(
        model_name=contract.embed_model,
        dimensions=contract.embed_dimensions,
        embed_library=contract.embed_library,
        cache_dir=str(workspace / "models"),
    )
    try:
        vectors = embedder.embed_documents(["The harbour lease was signed in March."])
    except Exception as exc:
        record("Real embedder loads", FAIL, f"{type(exc).__name__}: {exc}")
        return
    record("Real embedder loads", PASS, f"model {contract.embed_model}")

    width = len(vectors[0])
    if width != contract.embed_dimensions:
        record(
            "Contract width matches the model",
            FAIL,
            f"contract says {contract.embed_dimensions}, model produced {width} — "
            "the contract default is wrong and every corpus built on it is mis-sized",
        )
        return
    record("Contract width matches the model", PASS, f"{width} dimensions, as declared")

    # e5 is asymmetric: a passage and a query are prefixed differently, and
    # getting that backwards degrades retrieval quietly rather than loudly.
    query = embedder.embed_query("who signed the harbour lease")
    if len(query) != width:
        record("Query and passage widths agree", FAIL, f"query {len(query)} vs passage {width}")
        return
    record("Query and passage widths agree", PASS, f"both {width}")


def check_end_to_end(workspace: Path) -> None:
    """A real ingest with real embeddings, searched and cited.

    This is the claim the whole prototype rests on, and it has only ever been
    made against a stand-in embedder.
    """
    from jackryan.app import build_context
    from jackryan.config import Config, Contract, Profile

    config = Config(
        contract=Contract(),
        profile=Profile(name="verify", embedder="model"),
        data_dir=workspace / "data",
    )
    try:
        context = build_context(config)
    except Exception as exc:
        record("End-to-end with real embeddings", FAIL, f"context: {type(exc).__name__}: {exc}")
        return

    try:
        casefile = context.casefiles.create("Model Path Verification")
        corpus = workspace / "corpus"
        corpus.mkdir(exist_ok=True)
        (corpus / "lease.md").write_text(
            "# Harbour Lease\n\n"
            "Northgate Holdings was awarded the harbour lease in March 2021 "
            "by the port authority board.\n",
            encoding="utf-8",
        )
        (corpus / "lease.pdf").write_bytes(_pdf_bytes())

        report = context.ingestion.ingest(casefile.short_id, corpus)
        if report.failed:
            detail = "; ".join(o.detail for o in report.outcomes if o.status == "failed")
            record("End-to-end with real embeddings", FAIL, f"ingest failures: {detail}")
            return

        # This query shares content words with the corpus ("was", "awarded",
        # "lease"), so keyword retrieval alone could satisfy it. What the check
        # below establishes is that the vector leg ran and returned something —
        # `vector_rank` is set — not that semantic retrieval beat keywords.
        # Retrieval quality is a separate question and is not measured here.
        hits = context.search.search(casefile.short_id, "who was awarded the lease", limit=3)
        if not hits:
            record(
                "End-to-end with real embeddings",
                FAIL,
                "ingested but retrieved nothing for a paraphrased query",
            )
            return
        semantic = [h for h in hits if h.vector_rank is not None]
        record(
            "End-to-end with real embeddings",
            PASS,
            f"{report.ingested} documents, {len(hits)} hits, "
            f"{len(semantic)} found by vector search",
        )
    finally:
        context.close()


def check_mcp_surface(workspace: Path) -> None:
    """Whether an agent can be pointed at this instance at all.

    This script cannot verify the part that actually matters — that a live
    model *chooses* the right tools from their descriptions. It verifies the
    surface answers, which is the precondition. Driving it with two model
    vendors remains a human step; see docs/handover.md.
    """
    import anyio

    from jackryan.app import build_context
    from jackryan.config import Config, Contract, Profile
    from jackryan.interfaces.mcp import build_mcp_server

    config = Config(
        contract=Contract(),
        profile=Profile(name="verify", embedder="model"),
        data_dir=workspace / "mcp-data",
    )
    context = build_context(config)
    try:
        casefile = context.casefiles.create("Surface Check")
        corpus = workspace / "mcp-corpus"
        corpus.mkdir(exist_ok=True)
        (corpus / "note.md").write_text(
            "# Note\n\nThe port authority board deferred the tariff decision.\n",
            encoding="utf-8",
        )
        context.ingestion.ingest(casefile.short_id, corpus)
        server = build_mcp_server(context)

        async def drive():
            import json

            result = await server.call_tool(
                "case_search",
                {"casefile": casefile.short_id, "query": "what did the board defer", "limit": 3},
            )
            payload = json.loads(result.content[0].text)
            if not payload.get("results"):
                return None
            cited = await server.call_tool(
                "case_cite",
                {
                    "casefile": casefile.short_id,
                    "chunk_id": payload["results"][0]["chunk_id"],
                },
            )
            return json.loads(cited.content[0].text)

        citation = anyio.run(drive)
        if not citation or "citation" not in citation:
            record("MCP surface answers with a citation", FAIL, "search or cite returned nothing")
            return
        record("MCP surface answers with a citation", PASS, citation["citation"][:80])
    except Exception as exc:
        record("MCP surface answers with a citation", FAIL, f"{type(exc).__name__}: {exc}")
    finally:
        context.close()


CHECKS = {
    "pdf": ("PDF extraction (Docling layout models)", check_pdf_extraction),
    "ocr": ("Recognition of a scan in three languages", check_recognition),
    "embedder": ("The real embedder and the contract width", check_real_embedder),
    "end-to-end": ("A real ingest, searched with real vectors", check_end_to_end),
    "mcp": ("The MCP surface, driven in process", check_mcp_surface),
    "vlm": ("The vision rung, against a real model", check_vision_rung),
}

# Left out of a default run because it downloads hundreds of megabytes of model
# weights for a rung most documents never reach. Ask for it with `--only vlm`.
BY_REQUEST_ONLY = ("vlm",)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--only",
        choices=sorted(CHECKS),
        action="append",
        help="run one check rather than all of them; repeatable",
    )
    parser.add_argument("--keep", action="store_true", help="leave the temporary directory in place")
    args = parser.parse_args()

    selected = args.only or [key for key in CHECKS if key not in BY_REQUEST_ONLY]
    workspace = Path(tempfile.mkdtemp(prefix="jackryan-verify-"))
    print(f"Workspace: {workspace}\n")

    try:
        for key in selected:
            title, func = CHECKS[key]
            print(f"{title}")
            try:
                func(workspace)
            except Exception:
                record(title, FAIL, "raised before it could report")
                traceback.print_exc()
            print()
    finally:
        if args.keep:
            print(f"Left in place: {workspace}")
        else:
            shutil.rmtree(workspace, ignore_errors=True)

    failed = [r for r in results if r[1] == FAIL]
    passed = [r for r in results if r[1] == PASS]
    print("─" * 60)
    print(f"{len(passed)} passed, {len(failed)} failed")
    if failed:
        print("\nFailures:")
        for name, _, detail in failed:
            print(f"  ✗ {name}: {detail}")
        print(
            "\nA failure here is a real finding, not a flaky environment: these are "
            "the paths nothing else in this repository exercises."
        )
        return 1
    print(
        "\nThese claims now rest on something that ran, rather than on a deterministic "
        "stand-in. Record the result in docs/handover.md."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
